name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read the project file
        run: cat hello.txt

      - name: Open folder and read the file
        run: |
          cd test
          cat new.txt

      - name: Install PM2
        run: victorargento/pm2-deployment@main

      - name: Install helloSH
        run: sh ./hello.sh

      - name: Install NodeJS
        run: actions/setup-node@v6







