name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup-nginx:
    runs-on: self-hosted

    steps:
      - name: Install Nginx
        run: sudo apt install nginx -y

      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v5

      # - name: Read the project file
      #   run: cat hello.txt

      # # - name: Install PM2
      # #   uses: victorargento/pm2-deployment@main

      # - name: Install NodeJS
      #   uses: actions/setup-node@v5

      # - name: Install helloSH
      #   run: sh ./hello.sh

      







